CREATE TABLE clients (
    client_id   NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  NVARCHAR2(30) NOT NULL,
    last_name   NVARCHAR2(30) NOT NULL,
    phone       VARCHAR2(15) NOT NULL,
    email       VARCHAR2(50) NOT NULL
);
ALTER TABLE clients ADD CONSTRAINT clients_pk PRIMARY KEY (client_id);

CREATE TABLE employees (
    employee_id  NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   NVARCHAR2(30) NOT NULL,
    last_name    NVARCHAR2(30) NOT NULL,
    position     VARCHAR2(50) NOT NULL,
    phone        VARCHAR2(15) NOT NULL,
    email        VARCHAR2(50) NOT NULL,
    hire_date    DATE NOT NULL,
    salary       NUMBER(8, 2) NOT NULL
);
ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY (employee_id);

CREATE TABLE tours (
    tour_id      NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tour_name    VARCHAR2(50) NOT NULL,
    destination  VARCHAR2(50) NOT NULL,
    start_date   DATE NOT NULL,
    end_date     DATE NOT NULL,
    price        NUMBER(8, 2) NOT NULL
);
ALTER TABLE tours ADD CONSTRAINT tours_pk PRIMARY KEY (tour_id);

CREATE TABLE hotels (
    hotel_id    NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hotel_name  VARCHAR2(50) NOT NULL,
    location    VARCHAR2(50) NOT NULL,
    stars       NUMBER(1) NOT NULL,
    phone       VARCHAR2(15) NOT NULL,
    email       VARCHAR2(50) NOT NULL,
    tour_id     NUMBER NOT NULL
);
ALTER TABLE hotels ADD CONSTRAINT hotels_pk PRIMARY KEY (hotel_id);

CREATE TABLE meals (
    meal_id      NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tour_id      NUMBER NOT NULL,
    meal_type    VARCHAR2(30) NOT NULL,
    description  NVARCHAR2(250)
);
ALTER TABLE meals ADD CONSTRAINT meals_pk PRIMARY KEY (meal_id);

CREATE TABLE passport (
    passport_id      NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id        NUMBER NOT NULL,
    passport_number  NVARCHAR2(20) NOT NULL,
    issue_date       DATE NOT NULL,
    expiry_date      DATE NOT NULL,
    issuing_country  VARCHAR2(50) NOT NULL
);
ALTER TABLE passport ADD CONSTRAINT passport_pk PRIMARY KEY (passport_id);

CREATE TABLE bookings (
    booking_id    NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_date  DATE NOT NULL,
    client_id     NUMBER NOT NULL,
    tour_id       NUMBER NOT NULL,
    employee_id   NUMBER NOT NULL
);
ALTER TABLE bookings ADD CONSTRAINT bookings_pk PRIMARY KEY (booking_id);

CREATE TABLE payments (
    payment_id          NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id          NUMBER NOT NULL,
    amount              NUMBER(8, 2) NOT NULL,
    payment_date        DATE NOT NULL,
    transaction_number  VARCHAR2(100) NOT NULL,
    payment_method      VARCHAR2(50) NOT NULL,
    employee_id         NUMBER NOT NULL
);
ALTER TABLE payments ADD CONSTRAINT payments_pk PRIMARY KEY (payment_id);

CREATE TABLE transport (
    transport_id     NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transport_type   VARCHAR2(30) NOT NULL,
    route_number     VARCHAR2(20) NOT NULL,
    departure_date   DATE NOT NULL,
    departure_time   TIMESTAMP NOT NULL,
    departure_place  VARCHAR2(50) NOT NULL,
    arrival_place    VARCHAR2(50) NOT NULL,
    price            NUMBER(8, 2) NOT NULL,
    employee_id      NUMBER NOT NULL,
    tour_id          NUMBER NOT NULL
);
ALTER TABLE transport ADD CONSTRAINT transport_pk PRIMARY KEY (transport_id);


ALTER TABLE bookings
    ADD CONSTRAINT bookings_clients_fk FOREIGN KEY (client_id)
        REFERENCES clients (client_id) ON DELETE CASCADE;

ALTER TABLE bookings
    ADD CONSTRAINT bookings_employees_fk FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id) ON DELETE CASCADE;

ALTER TABLE bookings
    ADD CONSTRAINT bookings_tours_fk FOREIGN KEY (tour_id)
        REFERENCES tours (tour_id) ON DELETE CASCADE;

ALTER TABLE hotels
    ADD CONSTRAINT hotels_tours_fk FOREIGN KEY (tour_id)
        REFERENCES tours (tour_id) ON DELETE CASCADE;

ALTER TABLE meals
    ADD CONSTRAINT meals_tours_fk FOREIGN KEY (tour_id)
        REFERENCES tours (tour_id) ON DELETE CASCADE;

ALTER TABLE passport
    ADD CONSTRAINT passport_clients_fk FOREIGN KEY (client_id)
        REFERENCES clients (client_id) ON DELETE CASCADE;

ALTER TABLE payments
    ADD CONSTRAINT payments_bookings_fk FOREIGN KEY (booking_id)
        REFERENCES bookings (booking_id) ON DELETE CASCADE;

ALTER TABLE payments
    ADD CONSTRAINT payments_employees_fk FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id) ON DELETE CASCADE;

ALTER TABLE transport
    ADD CONSTRAINT transport_employees_fk FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id) ON DELETE CASCADE;

ALTER TABLE transport
    ADD CONSTRAINT transport_tours_fk FOREIGN KEY (tour_id)
        REFERENCES tours (tour_id) ON DELETE CASCADE;
		
COMMIT;